// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sqnvnolccwghpqrcezwf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxbnZub2xjY3dnaHBxcmNlendmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTU4MzIyNzQsImV4cCI6MjAzMTQwODI3NH0.16iurJUZXTcZU_gG47VNXheNa4BDy-zPvSMqxYAZn08";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);